server/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    resources :posts do
      get :publish
    end
  end
  resources :posts, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get 'static/welcome'
  root 'static#welcome'
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

server/app/models/post.rb
## The Post model, where microblog posts live
class Post < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "author_id"

  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :author

  scope :published, -> { where(published: true) }
  scope :drafts, -> { where(published: false) }

  def publish!
    self.published = true
    save!
  end
end

server/app/models/user.rb
## The User model
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, with: /.+@.+\.[a-z0-9]+\z/i
  validates_presence_of :password_digest

  has_many :posts, foreign_key: 'author_id', inverse_of: 'author'

  scope :admins, -> { where(admin: true) }

  def admin!
    self.admin = true
    save!
  end

  def self.superadmin
    admins.order(created_at: :asc).first
  end

  def superadmin?
    id == self.class.admins.order(created_at: :asc).first&.id
  end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize!
    redirect_to login_url, alert: "Not authorized" unless current_user.nil?
  end

  def superadmin
    User.admins.order(created_at: :asc).take(1)
  end

  def superadmin?
    current_user.present? && current_user.id = superamdin&.id
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

server/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_author
  before_action :set_post, only: [:show, :edit, :update, :publish, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = authorize @author.present? ? @author.posts.all : Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    authorize @post
  end

  # GET /posts/new
  def new
    @post = authorize @author.present? ? @author.posts.build : Post.new
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = authorize @author.present? ?
              @author.posts.build(post_params) :
              Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /posts/1/publish
  def publish
    authorize @post, :update?
    @post.publish!
    respond_to do |format|
      format.html { redirect_to @post, notice: "Post was successfully published." }
      format.json { render :show, status: :ok, location: @post }
    end
  end



  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = params[:user_id].present? ? User.find(params[:user_id]) : nil
  end

  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :published)
  end
end

server/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in"
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

server/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
    @posts = Post.published
  end
end

server/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = authorize User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user
  end

  # GET /users/new
  def new
    authorize User
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = authorize User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thanks for signing up"
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:handle, :email, :password, :password_confirmation)
  end
end

server/app/helpers/application_helper.rb
module ApplicationHelper

  def flash_style_type(key)
    case key
    when "notice"
      "info"
    when "alert"
      "danger"
    else
      "light"
    end
  end

end

server/app/helpers/sessions_helper.rb
module SessionsHelper
end

server/app/helpers/static_helper.rb
module StaticHelper
end

server/app/helpers/users_helper.rb
module UsersHelper
end

server/app/views/layouts/_debug.html.erb
<% if Rails.env.development? %>
  <hr />
  <pre>
    <code>
      DEBUGGING
      =========

      session[:user_id]: <%= session[:user_id] %>
    </code>
  </pre>
<% end %>

server/app/views/layouts/_flash_messages.html.erb
<%# Display the flash message in the page header %>
<% unless flash.empty? %>
  <% flash.each do |key, message| %>
    <% style = flash_style_type(key) %>
    <div class="alert alert-<%= style %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

server/app/views/layouts/_navtop.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="/">Miniblog Example</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
      <% if current_user&.admin? %>
        <li class="nav-item"><a class="nav-link" href="<%= users_path %>">Users</a></li>
      <% end %>
    </ul>
  </div>
</nav>

server/app/views/layouts/_page_body.html.erb
<main class="card" role="main">
  <% if content_for?(:content_title) %>
    <header class="card-header">
      <%= yield(:content_title) %>
    </header>
  <% end %>
  <section class="card-body">
    <%= content_for?(:content_body) ? yield(:content_body) : yield %>
  </section>
  <% if content_for?(:content_footer) %>
    <header class="card-footer">
      <%= yield(:content_footer) %>
    </header>
  <% end %>
</main>

server/app/views/layouts/_page_footer.html.erb
<footer class="d-flex justify-content-between align-items-center border-top">
  <% if current_user %>
    <div>
      <small>
        Logged in as
        <%= link_to current_user.handle, user_url(current_user) %>.</small></div>
    <div class="btn-group" role="group">
      <%= link_to "Log out", logout_url, class: "btn btn-sm btn-light" %>
    </div>
  <% else %>
    <div><small>Not logged in.</small></div>
    <div class="btn-group" role="group">
      <%= link_to "Log in", login_url, class: "btn btn-sm btn-primary" %>
      <%= link_to "Sign up", signup_url, class: "btn btn-sm btn-secondary" %>
    </div>
  <% end %>
</footer>

server/app/views/layouts/_page_header.html.erb
<header>
  <%= render "layouts/navtop" %>
  <%= render "layouts/flash_messages" %>
</header>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniblog Example</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head_area %>
  </head>

  <body class="container">
    <%= render template: "layouts/_page_header" %>
    <%= render template: "layouts/_page_body" %>
    <%= render template: "layouts/_page_footer" %>
    <%= yield :javascript %>
    <%= render template: "layouts/_debug" %>
  </body>
</html>

server/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= render partial: 'shared/form_errors', locals: { model: post } %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :published %>
    <%= form.check_box :published, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

server/app/views/posts/_post.html.erb
<tr>
  <td><%= post.title %></td>
  <td><%= post.content %></td>
  <% if current_user == @author %>
    <td><%= post.published %></td>
  <% end %>
  <td>
    <% if policy(post).show? %>
      <%= link_to 'Show', post %>
    <% end %>
  </td>
  <td>
    <% if policy(post).edit? %>
      <%= link_to 'Edit', edit_user_post_path(post, user_id: current_user&.id) %>
    <% end %>
  </td>
  <td>
    <% if policy(post).destroy? %>
      <%= link_to 'Destroy', user_post_path(post, user_id: current_user.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </td>
</tr>

server/app/views/posts/edit.html.erb
<%= content_for :content_title do %>
Editing Post
<% end %>

<%= content_for :content_body do %>
  <%= render 'form', post: @post %>
<% end %> %>

<%= content_for :content_footer do || %>
  <div class="d-flex flex-row-reverse">
    <div class="btn-group">
      <%= link_to 'Show', @post, class: "btn btn-secondary" %>
      <%= link_to 'Posts', user_posts_path(user_id: current_user?.id), class: "btn btn-secondary" %>
    </div>
  </div>
<% end %> %>

server/app/views/posts/index.html.erb
<%= content_for :content_title do %>
  <h1>Posts for <%= @author.handle %></h1>
<% end %>

<%= content_for :content_body do %>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <% if current_user == @author %>
          <th>Published</th>
        <% end %>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= render partial: 'post', collection: @posts %>
    </tbody>
  </table>
<% end %>

<%= content_for :content_footer do %>
  <% if policy(Post).create? %>
    <%= link_to 'New Post', new_user_post_path(user_id: current_user.id) %>
  <% end %>
<% end %>

server/app/views/posts/new.html.erb
<%= content_for :content_title do %>
  <h1>New Post</h1>
<% end %>

<%= content_for :content_body do %>
  <%= render 'form', post: @post %>
<% end %>

<%= content_for :content_footer do %>
  <% if current_user.present? %>
    <%= link_to 'Posts', user_posts_path(current_user), class: "btn btn-primary" %>
  <% end %>
<% end %>

server/app/views/posts/show.html.erb
<%= content_for :content_title do %>
  <%= @post.title %>
<% end %>

<%= content_for :content_body do %>
  <%= @post.content %>
<% end %>

<%= content_for :content_footer do %>
  <div class="button-group">
    <% if current_user.present? %>
      <%= link_to 'Edit', edit_user_post_path(@post, user_id: current_user.id), class: "btn btn-primary" %>
      <%= link_to 'Posts', user_posts_path(user_id: current_user.id), class: "btn btn-secondary" %>
    <% else %>
      <%= link_to 'Posts', posts_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

server/app/views/shared/_form_errors.html.erb
<%# model is the form model and must be passed as a local %>
<% if model.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

server/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%= render partial: 'shared/form_errors', locals: { model: @user } %>

  <div class="form-group">
    <%= form.label :handle %>
    <%= form.text_field :handle, class: "form-control", autofocus: true %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.text_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

server/app/views/users/_user.html.erb
<tr>
  <td><%= user.handle %></td>
  <td><%= user.email %></td>
  <td><%= link_to_if (policy(user).show?), 'Show', user %></td>
  <td><%= link_to_if (policy(user).edit?), 'Edit', edit_user_path(user) %></td>
  <td><%= link_to_if (policy(user).destroy?), 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

server/app/views/users/edit.html.erb
<div class="card">
  <div class="card-header">
    Editing User
  </div>
  <div class="card-body">
    <%= render 'form', user: @user %>
  </div>
  <div class="card-footer d-flex flex-row-reverse">
    <div class="button-group">
      <%= link_to 'Show', @user, class: "btn btn-secondary" %>
      <%= link_to 'Users', users_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

server/app/views/users/index.html.erb
<div class="card">
  <div class="card-header">
    <h1>Users</h1>
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>Handle</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "user", collection: @users %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= link_to 'New User', new_user_path, class: "btn btn-success" %>
  </div>
</div>

server/app/views/users/new.html.erb
<h1>Sign up as a new user:</h1>

<%= render 'form', user: @user %>

server/app/views/users/show.html.erb
<div class="card">
  <div class="card-body">
    <h3>User <%= @user.handle %></h3>
    <p>Email: <%= @user.email %></p>
    <p>Joined: <%= @user.created_at.to_s %></p>
  </div>
  <div class="card-footer d-flex flex-row-reverse">
    <div class="button-group">
      <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-secondary" %>
      <%= link_to 'Users', users_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>